# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('events', '0002_pollpluginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='events_eventspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='pollpluginmodel',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='pollpluginmodel',
            name='event',
        ),
        migrations.DeleteModel(
            name='PollPluginModel',
        ),
    ]
